// OECD 32 countries (ISO3 code and display name)
// Note: You can adjust this list as needed
const List<Map<String, String>> oecdCountries = [
  {'code': 'AUS', 'name': 'Australia'},
  {'code': 'AUT', 'name': 'Austria'},
  {'code': 'BEL', 'name': 'Belgium'},
  {'code': 'CAN', 'name': 'Canada'},
  {'code': 'CHL', 'name': 'Chile'},
  {'code': 'CZE', 'name': 'Czech Republic'},
  {'code': 'DNK', 'name': 'Denmark'},
  {'code': 'EST', 'name': 'Estonia'},
  {'code': 'FIN', 'name': 'Finland'},
  {'code': 'FRA', 'name': 'France'},
  {'code': 'DEU', 'name': 'Germany'},
  {'code': 'GRC', 'name': 'Greece'},
  {'code': 'HUN', 'name': 'Hungary'},
  {'code': 'ISL', 'name': 'Iceland'},
  {'code': 'IRL', 'name': 'Ireland'},
  {'code': 'ISR', 'name': 'Israel'},
  {'code': 'ITA', 'name': 'Italy'},
  {'code': 'JPN', 'name': 'Japan'},
  {'code': 'KOR', 'name': 'Korea, Rep.'},
  {'code': 'LVA', 'name': 'Latvia'},
  {'code': 'LTU', 'name': 'Lithuania'},
  {'code': 'LUX', 'name': 'Luxembourg'},
  {'code': 'MEX', 'name': 'Mexico'},
  {'code': 'NLD', 'name': 'Netherlands'},
  {'code': 'NZL', 'name': 'New Zealand'},
  {'code': 'NOR', 'name': 'Norway'},
  {'code': 'POL', 'name': 'Poland'},
  {'code': 'PRT', 'name': 'Portugal'},
  {'code': 'SVK', 'name': 'Slovak Republic'},
  {'code': 'SVN', 'name': 'Slovenia'},
  {'code': 'ESP', 'name': 'Spain'},
  {'code': 'SWE', 'name': 'Sweden'},
];
